name: Backpacks
main: com.github.neapovil.backpacks.Backpacks
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/Backpacks
depend:
  - CommandAPI
permissions:
  backpacks.command:
    default: op
